#!/bin/bash

set -e

fname="${4} - ${2}.ogg"
fname="${fname//\//-}"
cat > "${fname}"
echo "${fname}"
{
	echo "SPOTIFY_ID=${1}"
	title="${2//'\n'/' '}"
	album="${3//'\n'/' '}"
	echo "TITLE=${title}"
	echo "ALBUM=${album}"
	shift 3
	for artist in "$@"; do
		artist="${artist//'\n'/' '}"
		echo "ARTIST=${artist}"
	done
} | vorbiscomment -a "${fname}"
