#!/bin/sh

set -e

fname=$(echo "${2} - ${1}.ogg" | tr '/' - | tr '\0' ' ')
cat > "$fname"
{
	echo "TITLE=${1}" | tr '\n' ' '
	shift
	for artist in "$@"; do
		echo "ARTIST=${artist}" | tr '\n' ' '
	done
} | vorbiscomment -a "$fname"
