#!/bin/sh

set -e

fname=$(echo "${4} - ${2}.ogg" | tr '/' - | tr '\0' ' ')
cat > "$fname"
echo "$fname"
{
	echo "SPOTIFY_ID=${1}"
	title=$(tr '\n' ' ' <<< "${2}")
	album=$(tr '\n' ' ' <<< "${3}")
	echo "TITLE=${title}"
	echo "ALBUM=${album}"
	shift 3
	for artist in "$@"; do
		artist=$(tr '\n' ' ' <<< "${artist}")
		echo "ARTIST=${artist}"
	done
} | vorbiscomment -a "$fname"
